### ISSUE TITLE
travis build fails

### ISSUE THREAD

**Issue by fedonman** [codeandwork/courses#11]
travis build always fails and stops at:
`Building web/java/html5.html`

I tried to change the file to fix it but still failing.

[full log](https://api.travis-ci.org/jobs/172617029/log.txt?deansi=true)

**Comment by dspinellis** [comment]
Local build works OK.  Could be a Travis glitch.  Rebuilding.

**Comment by dspinellis** [comment]
From the detailed log, it seems than `pandoc` is not responding.

**Comment by dspinellis** [comment]
I reproduced the problem on Debian GNU/Linux 8.6 (jessie), pandoc 1.12.4.2.

@fedonman If you have access to such an environment can you please prune your input file until you find and eliminate the part that causes pandoc to freeze?  The command to run is:

```
pandoc -f markdown_github -t html html5.md
```

Then consider filing a bug with `pandoc`.

**Comment by fedonman** [comment]
travis builds successfuly
